[versions]
# Core
activity-compose = "1.12.0-alpha04"
fragment-compose = "1.8.8"
appcompat = "1.7.1"
kotlin = "2.1.21"
kotlin-core = "1.16.0"
kotlin-serialization = "1.8.1"
constraint-compose = "1.1.1"

# Firebase
firebase-analytics = "22.5.0"
firebase-crashlytics = "19.4.4"
firebaseAuthKtx = "23.2.1"
firebaseFirestoreKtx = "25.1.4"
firebaseDatabaseKtx = "21.0.0"
firebaseStorageKtx = "21.0.2"
firebase-messaging = "24.1.2"
firebase-crashlytics-plugin = "3.0.4"

# Material Design
material = "1.12.0"
nav3Material = "1.0.0-alpha01"
materialIconsExtended = "1.7.8"
material3 = "1.3.2"
material3-windowsizeclass = "1.3.2"
material3-adaptive = "1.2.0-alpha08"
material3-adaptive-navigation = "1.1.0"
material3-adaptive-suite = "1.3.2"

# Navigation
nav3Core = "1.0.0-alpha05"

# Lifecycle:
lifecycle = "2.9.1"
lifecycle-runtime = "2.9.1"
livedata-runtime = "1.8.3"
lifecycle-nav3 = "1.0.0-alpha03"

# Google
accompanist = "0.36.0"
googleServices = "4.4.3"

# Hilt
hilt = "2.54"
hilt-navigation = "1.2.0"

# Retrofit
retrofit = "2.11.0"
retrofit-gson = "2.9.0"
okhttp = "4.12.0"
retrofitConverterFactory = "0.8.0"

# Compose
ui = "1.8.3"
ui-graphics = "1.8.3"
ui-tooling = "1.8.3"
ui-tooling-preview = "1.8.3"
ui-text-google-fonts = "1.8.3"

#Room
room = "2.7.2"
room-ktx = "2.7.2"
room-compiler = "2.7.2"

# Credentials:
credentials = "1.5.0"
credentialsPlayServicesAuth = "1.5.0"
playServicesAuth = "21.3.0"
googleid = "1.1.1"

# Datastore:
datastore = "1.1.7"
protobuf = "4.29.2"
protobufPlugin = "0.9.4"

# Coil:
coil = "2.7.0"

# Lottie:
lottie = "6.6.0"

# Couchbase
couchbase = "3.2.0"

# Testing (No changes versions without pass the tests)
espresso-core = "3.6.1"
junit = "1.2.1"
androidxTestCore = "1.6.1"
testRunner = "1.6.2"
testRules = "1.6.1"
mockito = "5.12.0"
mockito-kotlin = "5.4.0"
turbine = "1.2.0"
kotlin-coroutine-tests = "1.9.0"
reflectionsTest = "0.10.2"

# Plugins
androidAppPluginVersion = "8.13.0"
androidGradlePlugin = "8.6.1"
androidToolsCommon = "31.11.0"
kotlin-gradle-plugin = "2.2.0-RC3"
ksp = "2.2.0-RC3-2.0.2"
kspGradlePlugin = "2.1.0-1.0.29"
benmanes-versions = "0.51.0"
dependency-analyze = "1.10.0"
junitVersion = "4.13.2"

[libraries]
# Core
activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
fragment = { group = "androidx.fragment", name = "fragment-compose", version.ref = "fragment-compose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "kotlin-core" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraint-compose" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

# Firebase
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebase-crashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx", version.ref = "firebase-messaging" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
firebase-database = { module = "com.google.firebase:firebase-database-ktx", version.ref = "firebaseDatabaseKtx" }
firebase-storage = { module = "com.google.firebase:firebase-storage-ktx", version.ref = "firebaseStorageKtx" }

# Lifecycle:
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-nav3 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "lifecycle-nav3" }
livedata-runtime = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "livedata-runtime" }

# Compose
ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "ui-tooling-preview" }
ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "ui-text-google-fonts" }

# Material Design
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material3-windowsizeclass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3-windowsizeclass" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "material3-adaptive" }
material3-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "material3-adaptive" }
material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "material3-adaptive-navigation" }
material3-adaptive-navigation-suite-android = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite-android", version.ref = "material3-adaptive-suite" }

# Navigation
navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "nav3Core" }
navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "nav3Core" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation" }

#Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit-gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit-converter-factory = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofitConverterFactory" }

# Credentials:
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }

# Accompanist
accompanist = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room-ktx" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-compiler" }

# Datastore
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }

# Couchbase
couchbase = { group = "com.couchbase.lite", name = "couchbase-lite-android", version.ref = "couchbase" }

# Coil:
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

# Lottie:
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

# Testing
junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
test-core = { group = "androidx.test", name = "core-ktx", version.ref = "androidxTestCore" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "testRules" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
kotlinx-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlin-coroutine-tests" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
reflections-test = { group = "org.reflections", name = "reflections", version.ref = "reflectionsTest" }

# Plugins
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidToolsCommon" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "kspGradlePlugin" }
junit-junit = { group = "junit", name = "junit", version.ref = "junitVersion" }

[plugins]
#Android
android-application = { id = "com.android.application", version.ref = "androidAppPluginVersion" }
android-library = { id = "com.android.library", version.ref = "androidAppPluginVersion" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.0.21" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
benmanes-versions = { id = "com.github.ben-manes.versions", version.ref = "benmanes-versions" }
dependency-analyze = { id = "ca.cutterslade.analyze", version.ref = "dependency-analyze" }

# Firebase
firebase-gms = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }

# Hilt
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

#Compose
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

#Protobuf
protobuf = { id = "com.google.protobuf" ,version.ref = "protobufPlugin" }

# My plugins
# Modules
buildlogic-application = { id = "buildlogic.android.application", version = "null" }
buildlogic-core = { id = "buildlogic.android.core", version = "null"}
buildlogic-feature = { id = "buildlogic.android.feature", version = "null"}
buildlogic-data = { id = "buildlogic.android.data", version = "null"}
buildlogic-domain = { id = "buildlogic.android.domain", version = "null"}

# Libraries
buildlogic-library = { id = "buildlogic.android.library", version = "null"}
buildlogic-hilt = { id = "buildlogic.android.hilt", version = "null"}
buildlogic-firebase = { id = "buildlogic.android.firebase", version = "null"}
buildlogic-retrofit = { id = "buildlogic.android.retrofit", version = "null"}
buildlogic-compose = { id = "buildlogic.android.compose", version = "null"}
buildlogic-credential = { id = "buildlogic.android.credential", version = "null"}
buildlogic-datastore = { id = "buildlogic.android.datastore", version = "null"}
buildlogic-couchbase = { id = "buildlogic.android.couchbase", version = "null"}
buildlogic-lifecycle = { id = "buildlogic.android.lifecycle", version = "null"}
buildlogic-material = { id = "buildlogic.android.material", version = "null"}
buildlogic-navigation = { id = "buildlogic.android.navigation", version = "null"}
buildlogic-unit-test = { id = "buildlogic.android.unit.test", version = "null"}

# Flavors
buildlogic-flavors = { id = "buildlogic.android.flavors", version = "null"}
